# ---------------------------------------------------------------------------
# ElastiCache Redis — used by Socket.IO Redis Adapter (multi-pod event bus)
# and the server-side rate limiter fallback.
#
# Placement: private subnets only. The security group allows inbound 6379
# exclusively from EKS nodes; no public access.
#
# HA: Replication Group with automatic_failover and multi_az for AZ redundancy.
# ---------------------------------------------------------------------------

# Security group: allow Redis traffic only from EKS nodes.
resource "aws_security_group" "redis" {
  name        = "${var.cluster_name}-redis"
  description = "Allow Redis traffic from EKS nodes only"
  vpc_id      = module.vpc.vpc_id

  ingress {
    description     = "Redis from EKS nodes"
    from_port       = 6379
    to_port         = 6379
    protocol        = "tcp"
    security_groups = [module.eks.node_security_group_id]
  }

  # CIS AWS Foundations Benchmark 5.4: restrict egress to VPC CIDR only.
  # Redis does not initiate outbound internet connections.
  egress {
    description = "Allow outbound only within VPC"
    from_port   = 0
    to_port     = 0
    protocol    = "-1"
    cidr_blocks = [module.vpc.vpc_cidr_block]
  }

  tags = merge(var.tags, { Name = "${var.cluster_name}-redis" })
}

resource "aws_elasticache_subnet_group" "redis" {
  name       = "${var.cluster_name}-redis"
  subnet_ids = module.vpc.private_subnets
}

# Replication Group: primary + 1 replica across AZs, automatic failover.
resource "aws_elasticache_replication_group" "redis" {
  replication_group_id = "${var.cluster_name}-redis"
  description          = "AI Village Redis HA replication group"

  engine               = "redis"
  engine_version       = "7.1"
  node_type            = var.redis_node_type
  num_cache_clusters   = 2    # primary + 1 replica
  parameter_group_name = "default.redis7"
  port                 = 6379

  subnet_group_name  = aws_elasticache_subnet_group.redis.name
  security_group_ids = [aws_security_group.redis.id]

  automatic_failover_enabled = true
  multi_az_enabled           = true

  # Retain 7 days of automatic snapshots
  snapshot_retention_limit = 7
  snapshot_window          = "02:00-03:00"   # UTC — different from RDS to spread load
  maintenance_window       = "sun:05:00-sun:06:00"

  apply_immediately = false   # apply during maintenance window in production

  at_rest_encryption_enabled  = true
  transit_encryption_enabled  = true
  transit_encryption_mode     = "required"

  # Redis AUTH token — defense-in-depth against node compromise or future SG misconfiguration.
  # Generated by random_password in secrets.tf; stored in Secrets Manager as ai-village/redis-auth-token.
  # (AWS Security Hub ElastiCache.3 / CIS AWS Benchmark)
  auth_token                  = random_password.redis_auth.result
  auth_token_update_strategy  = "ROTATE"   # SET → ROTATE: cluster already has a token; ROTATE keeps old valid during transition

  tags = merge(var.tags, { Name = "${var.cluster_name}-redis" })
}
